### ISSUE TITLE
Travis & OpenSSL 1.0.2 & 1.1.0

### ISSUE THREAD

**Issue by MSP-Greg** [eventmachine/eventmachine#790]
While working on Travis CI (I"m a windows guy) for the recent PR for 1.1.0, I noticed that most of the ruby builds seem to be using OpenSSL 1.0.1.  Per the [OpenSSL web site](https://www.openssl.org/source/),  'The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be used.'

I noticed that the Ruby OpenSSL gem has the following in its [travis.yml](https://github.com/ruby/openssl/blob/master/.travis.yml) file:
```
--
matrix:
  fast_finish: true
  include:
    - env: RUBY_VERSION=ruby-2.3 OPENSSL_VERSION=openssl-1.0.2
    - env: RUBY_VERSION=ruby-2.4 OPENSSL_VERSION=openssl-1.0.1
    - env: RUBY_VERSION=ruby-2.4 OPENSSL_VERSION=openssl-1.0.2
    - env: RUBY_VERSION=ruby-2.4 OPENSSL_VERSION=openssl-1.1.0
```

I'm not familiar with travis scripts, but it sure looks like they're building/testing against 1.0.2 and 1.1.0.  Might be something to look into for EM...
